name = "pumpkin-jam-proxy"
main = "worker.js"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGINS = "https://www.clicktorelease.com,https://clicktorelease.com,https://spite.github.io"

[[kv_namespaces]]
binding = "TOKENS"
id = "e00013db6aeb469d9a92aa9f4b0e04bf"

[[ratelimits]]
name = "LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 20
  period = 60
